# SwiftLint Configuration for HomeCooked
# https://github.com/realm/SwiftLint

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - DerivedData
  - HomeCooked.xcodeproj
  - "*/xcshareddata/*"
  - "*/xcuserdata/*"

# Paths to include (optional - by default all Swift files)
included:
  - App
  - CLIs
  - Packages
  - Tests

# Enabled rules (in addition to default rules)
opt_in_rules:
  - explicit_init
  - explicit_type_interface
  - file_header
  - missing_docs
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Disabled rules
disabled_rules:
  - todo  # Allow TODO comments (they're tracked separately)
  - line_length  # Handled by swiftformat

# Rule configurations
identifier_name:
  min_length: 1  # Allow single-letter names (e.g., in closures)
  excluded:
    - id
    - db
    - os
    - x
    - y
    - i
    - j
    - k

type_name:
  min_length: 2
  max_length: 50

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Require documentation for public declarations
missing_docs:
  warning:
    - public
    - open
  excludes_extensions: true
  excludes_inherited_types: true

# File header comments
file_header:
  required_pattern: |
                    \/\/ .*\.swift
                    \/\/ .*

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '(?<!\/\/.*)(^|\s)print\s*\('
    message: "Use proper logging instead of print()"
    severity: warning

  mark_format:
    name: "MARK Format"
    regex: '\/\/\s*MARK:\s*[^-\s]'
    message: "MARK comments should use format: // MARK: - Section Name"
    severity: warning

# Severity overrides
force_cast: error
force_try: error
force_unwrapping: warning

# Reporter type
reporter: "xcode"
