name: HomeCooked
options:
  bundleIdPrefix: com.homecooked
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.1"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_STRICT_OBJC_MSGSEND: YES
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  HomeCookedPackage:
    path: .

targets:
  HomeCooked:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: App
        excludes:
          - "**/*.md"
          - "**/Package.swift"

    info:
      path: App/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: HomeCooked
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false

    dependencies:
      - package: HomeCookedPackage
        product: Domain
      - package: HomeCookedPackage
        product: UseCases
      - package: HomeCookedPackage
        product: PersistenceInterfaces
      - package: HomeCookedPackage
        product: PersistenceGRDB
      - package: HomeCookedPackage
        product: ImportExport
      - package: HomeCookedPackage
        product: SyncInterfaces
      - package: HomeCookedPackage
        product: SyncCloudKit

    settings:
      base:
        PRODUCT_NAME: HomeCooked
        PRODUCT_BUNDLE_IDENTIFIER: com.homecooked.app
        INFOPLIST_FILE: App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"

      debug:
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG

      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        SWIFT_COMPILATION_MODE: wholemodule

schemes:
  HomeCooked:
    build:
      targets:
        HomeCooked: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
